# Generated by Django 5.1.3 on 2024-12-03 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_diretório_subdiretório_arquivo"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Diretório",
            new_name="Diretorio",
        ),
        migrations.RenameModel(
            old_name="Subdiretório",
            new_name="Subdiretorio",
        ),
    ]
