# Generated by Django 5.1.3 on 2024-12-03 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_rename_diretório_diretorio_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="arquivo",
            name="arquivo",
            field=models.FileField(upload_to="Arquivos/", verbose_name="Arquivo"),
        ),
    ]
