# Generated by Django 5.1.3 on 2024-12-03 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_arquivo_arquivo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="arquivo",
            name="arquivo",
            field=models.FileField(
                upload_to="dataroomclouds3/arquivos/", verbose_name="Arquivo"
            ),
        ),
    ]
