# Generated by Django 5.1.3 on 2024-12-03 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_alter_arquivo_arquivo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="arquivo",
            name="arquivo",
            field=models.FileField(upload_to="arquivos/", verbose_name="Arquivo"),
        ),
    ]
