# Generated by Django 5.1.3 on 2024-12-04 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_alter_arquivo_arquivo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="arquivo",
            name="arquivo",
            field=models.FileField(
                upload_to="s3.dataroomclouds3/", verbose_name="Arquivo"
            ),
        ),
    ]
