# Generated by Django 5.1.3 on 2024-12-05 15:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_alter_arquivo_arquivo"),
    ]

    operations = [
        migrations.CreateModel(
            name="Consideracao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "descricao",
                    models.TextField(blank=True, null=True, verbose_name="Descrição"),
                ),
                (
                    "arquivo_consideracao",
                    models.FileField(
                        upload_to="consideracoes/",
                        verbose_name="Arquivo da Consideração",
                    ),
                ),
                (
                    "data_envio",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Envio"
                    ),
                ),
                (
                    "arquivo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consideracoes",
                        to="core.arquivo",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Consideração",
                "verbose_name_plural": "Considerações",
            },
        ),
    ]
