# Generated by Django 5.1.3 on 2024-12-05 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_consideracao"),
    ]

    operations = [
        migrations.AddField(
            model_name="consideracao",
            name="is_aprovada",
            field=models.BooleanField(default=False),
        ),
    ]
