# Generated by Django 5.1.3 on 2024-12-05 17:00

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_consideracao_is_aprovada"),
    ]

    operations = [
        migrations.CreateModel(
            name="FileActionLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file_name",
                    models.CharField(max_length=255, verbose_name="Nome do Arquivo"),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("CREATE", "Upload de Arquivo"),
                            ("DELETE", "Exclusão de Arquivo"),
                            ("DOWNLOAD", "Download de Arquivo"),
                        ],
                        max_length=20,
                        verbose_name="Ação",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Data e Hora"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Log de Arquivo",
                "verbose_name_plural": "Logs de Arquivos",
            },
        ),
    ]
