# Generated by Django 5.1.3 on 2024-12-05 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_fileactionlog"),
    ]

    operations = [
        migrations.DeleteModel(
            name="FileActionLog",
        ),
    ]
